site_name: BDI Micro Credit Prompt Library

theme:
  name: material
  features:
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details

nav:
  - Home: index.md
  - Exercise 3-1: prompt-engineering-01.md
  - Exercise 4-1: search-techniques.md
  - Exercise 4-2: fact-checking.md
  - Exercise 5-1: claude-document-understanding.md

extra_css:
  - stylesheets/extra.css