site_name: BDI Micro Credit Prompt Library

theme:
  name: material
  features:
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details

nav:
  - Home: index.md
  - Exercise 3-1: prompt-engineering-exercise-01.md

extra_css:
  - stylesheets/extra.css